execute run bossbar set minecraft:1 name [{"text":"Vie : "},{"score":{"name":"@e[scores={player_id=1}]","objective":"PV"}},{"text":"/20                                                                                                             "}]
execute run bossbar set minecraft:2 name [{"text":"Vie : "},{"score":{"name":"@e[scores={player_id=2}]","objective":"PV"}},{"text":"/20                                                                                                             "}]
execute run bossbar set minecraft:3 name [{"text":"Vie : "},{"score":{"name":"@e[scores={player_id=3}]","objective":"PV"}},{"text":"/20                                                                                                             "}]
execute run bossbar set minecraft:4 name [{"text":"Vie : "},{"score":{"name":"@e[scores={player_id=4}]","objective":"PV"}},{"text":"/20                                                                                                             "}]
execute run bossbar set minecraft:5 name [{"text":"Vie : "},{"score":{"name":"@e[scores={player_id=5}]","objective":"PV"}},{"text":"/20                                                                                                             "}]
execute run bossbar set minecraft:6 name [{"text":"Vie : "},{"score":{"name":"@e[scores={player_id=6}]","objective":"PV"}},{"text":"/20                                                                                                             "}]
execute run bossbar set minecraft:7 name [{"text":"Vie : "},{"score":{"name":"@e[scores={player_id=7}]","objective":"PV"}},{"text":"/20                                                                                                             "}]
execute run bossbar set minecraft:8 name [{"text":"Vie : "},{"score":{"name":"@e[scores={player_id=8}]","objective":"PV"}},{"text":"/20                                                                                                             "}]
execute run bossbar set minecraft:9 name [{"text":"Vie : "},{"score":{"name":"@e[scores={player_id=9}]","objective":"PV"}},{"text":"/20                                                                                                             "}]
execute run bossbar set minecraft:10 name [{"text":"Vie : "},{"score":{"name":"@e[scores={player_id=10}]","objective":"PV"}},{"text":"/20                                                                                                             "}]

#"/20                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "
#"/20                                                                                                                                                                                                                                    "
#"/20                                                                                                                                                      "
#"/20                                                                                                              "
